title: "Das lebende Stimmrecht – Vom Untertan zum Auftraggeber"
subtitle: ""
author: "Asterios Raptis"
isbn:
  ebook: ""
  paperback: ""
  hardcover: ""
edition: "1"
publisher: ""
date: "2025"
language: "en"
description: "Konzept und Grundlagen eines Bürgerstaates, in dem Macht beim Menschen verbleibt: das lebende Stimmrecht als permanente, unverlierbare Form demokratischer Teilhabe. Kein Parteienstaat, sondern echte Souveränität. Analyse des alten Systems und Architektur der Machtumkehr zugunsten der Bürger."
keywords: []
cover_image: "assets/covers/cover.png"
output_formats: ["pdf", "epub", "docx"]
kdp_enabled: false
