name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pipx install poetry

      - name: Install deps
        run: poetry install --with dev

      - name: Lint (ruff/black)
        run: |
          poetry run ruff check .
          poetry run black --check .

      - name: Type check (mypy via pre-commit)
        run: poetry run pre-commit run mypy --all-files

      - name: Tests
        run: poetry run pytest -q --maxfail=1 --disable-warnings --cov=./ --cov-report=xml

      - name: Security (pip-audit & bandit)
        run: |
          poetry run pip-audit || true
          poetry run bandit -q -r scripts || true
